item {
    name: "Large Tire",
    id: 1,
    display_name: "Large Tire"
}
item {
    name: "Small Tire",
    id: 2,
    display_name: "Small Tire"
}
item {
    name: "damaged",
    id: 3,
    display_name: "damaged"
}
item {
    name: "notDamaged",
    id: 4,
    display_name: "notDamaged"
}
